/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.wolf.test.avro.generateclass;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface MemberIFace {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"MemberIFace\",\"namespace\":\"com.wolf.test.hadoop.avro.generateclass\",\"types\":[{\"type\":\"record\",\"name\":\"Members\",\"fields\":[{\"name\":\"userName\",\"type\":\"string\"},{\"name\":\"userPwd\",\"type\":\"string\"},{\"name\":\"realName\",\"type\":[\"string\",\"null\"]}]},{\"type\":\"record\",\"name\":\"Retmsg\",\"fields\":[{\"name\":\"msg\",\"type\":\"string\"}]}],\"messages\":{\"login\":{\"doc\":\"member login.\",\"request\":[{\"name\":\"m\",\"type\":\"Members\"}],\"response\":\"Retmsg\"}}}");
  /** member login. */
  Retmsg login(Members m) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends MemberIFace {
    public static final org.apache.avro.Protocol PROTOCOL = MemberIFace.PROTOCOL;
    /** member login. */
    void login(Members m, org.apache.avro.ipc.Callback<Retmsg> callback) throws java.io.IOException;
  }
}